// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArodDrmoC5nguIMOqNuQZb4ZqV0--Cwyc',
    appId: '1:568587829733:web:7a187d9f2987a911432f0c',
    messagingSenderId: '568587829733',
    projectId: 'auth-with-riverpod',
    authDomain: 'auth-with-riverpod.firebaseapp.com',
    storageBucket: 'auth-with-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyzhH1WqG7NoFfn60bgqgQp6d25RJAPf8',
    appId: '1:568587829733:android:c6ae66b531ae3446432f0c',
    messagingSenderId: '568587829733',
    projectId: 'auth-with-riverpod',
    storageBucket: 'auth-with-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBz73u2H6U-fj6_uyFQRWHoyNMofRTH0',
    appId: '1:568587829733:ios:cfbde4f97fc1a67d432f0c',
    messagingSenderId: '568587829733',
    projectId: 'auth-with-riverpod',
    storageBucket: 'auth-with-riverpod.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBz73u2H6U-fj6_uyFQRWHoyNMofRTH0',
    appId: '1:568587829733:ios:cfbde4f97fc1a67d432f0c',
    messagingSenderId: '568587829733',
    projectId: 'auth-with-riverpod',
    storageBucket: 'auth-with-riverpod.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArodDrmoC5nguIMOqNuQZb4ZqV0--Cwyc',
    appId: '1:568587829733:web:fb44e1e766823d67432f0c',
    messagingSenderId: '568587829733',
    projectId: 'auth-with-riverpod',
    authDomain: 'auth-with-riverpod.firebaseapp.com',
    storageBucket: 'auth-with-riverpod.appspot.com',
  );

}